name: mineLog
main: mineLog.MineLog
version: 1.0.1
commands:
   hello:
      description: This is a demo command.
      usage: /hello
      permission: builder
      permission-message: You don't have <permission>
   log:
      description: main command of mineLog
      usage: /log
      permission: mineLog.log
      permission-message: You don't have permisson <permission>